<?php

use Illuminate\Database\Seeder;

class ChatterTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run()
    {
        // CREATE THE CATEGORIES

        \DB::table('chatter_categories')->delete();

        \DB::table('chatter_categories')->insert([
            0 => [

                'parent_id'  => null,
                'order'      => 1,
                'name'       => 'Fast Moving Consumer Goods',
                'color'      => '#3498DB',
                'slug'       => 'fmcg',
                'created_at' => null,
                'updated_at' => null,
            ],
            1 => [

                'parent_id'  => null,
                'order'      => 2,
                'name'       => 'Oil and Gas',
                'color'      => '#2ECC71',
                'slug'       => 'oil_and_gas',
                'created_at' => null,
                'updated_at' => null,
            ],
            2 => [
                'parent_id'  => null,
                'order'      => 3,
                'name'       => 'Financial Services',
                'color'      => '#9B59B6',
                'slug'       => 'financial_services',
                'created_at' => null,
                'updated_at' => null,
            ],
            3 => [
                'parent_id'  => null,
                'order'      => 4,
                'name'       => 'Information Technology',
                'color'      => '#E67E22',
                'slug'       => 'information_technology',
                'created_at' => null,
                'updated_at' => null,
            ],
            4 => [
                'parent_id'  => null,
                'order'      => 1,
                'name'       => 'Media',
                'color'      => '#3498DB',
                'slug'       => 'media',
                'created_at' => null,
                'updated_at' => null,
            ],
            5 => [
                'parent_id'  => null,
                'order'      => 2,
                'name'       => 'Telecommunications',
                'color'      => '#2ECC71',
                'slug'       => 'telecommunications',
                'created_at' => null,
                'updated_at' => null,
            ],
            6 => [
                'parent_id'  => null,
                'order'      => 3,
                'name'       => 'Consulting',
                'color'      => '#9B59B6',
                'slug'       => 'consulting',
                'created_at' => null,
                'updated_at' => null,
            ],
            7 => [
                'parent_id'  => null,
                'order'      => 4,
                'name'       => 'Non-Profit',
                'color'      => '#E67E22',
                'slug'       => 'non_profit',
                'created_at' => null,
                'updated_at' => null,
            ],
            8 => [
                'parent_id'  => null,
                'order'      => 1,
                'name'       => 'Construction',
                'color'      => '#3498DB',
                'slug'       => 'construction',
                'created_at' => null,
                'updated_at' => null,
            ],
            9 => [
                'parent_id'  => null,
                'order'      => 2,
                'name'       => 'Pharmaceuticals',
                'color'      => '#2ECC71',
                'slug'       => 'pharmaceuticals',
                'created_at' => null,
                'updated_at' => null,
            ],
            10 => [
                'parent_id'  => null,
                'order'      => 3,
                'name'       => 'Hospitality/Tourism',
                'color'      => '#9B59B6',
                'slug'       => 'hospitality_tourism',
                'created_at' => null,
                'updated_at' => null,
            ],
            11 => [
                'parent_id'  => null,
                'order'      => 4,
                'name'       => 'Electricity/Energy',
                'color'      => '#E67E22',
                'slug'       => 'information_technology',
                'created_at' => null,
                'updated_at' => null,
            ],
            12 => [
                'parent_id'  => null,
                'order'      => 1,
                'name'       => 'Aviation',
                'color'      => '#3498DB',
                'slug'       => 'aviation',
                'created_at' => null,
                'updated_at' => null,
            ],
            13 => [
                'parent_id'  => null,
                'order'      => 2,
                'name'       => 'Agriculture',
                'color'      => '#2ECC71',
                'slug'       => 'agriculture',
                'created_at' => null,
                'updated_at' => null,
            ],
            14 => [
                'parent_id'  => null,
                'order'      => 3,
                'name'       => 'Government',
                'color'      => '#9B59B6',
                'slug'       => 'government',
                'created_at' => null,
                'updated_at' => null,
            ],
            15 => [
                'parent_id'  => null,
                'order'      => 4,
                'name'       => 'Insurance',
                'color'      => '#E67E22',
                'slug'       => 'insurance',
                'created_at' => null,
                'updated_at' => null,
            ],
            16 => [
                'parent_id'  => null,
                'order'      => 1,
                'name'       => 'Transportation',
                'color'      => '#3498DB',
                'slug'       => 'transportation',
                'created_at' => null,
                'updated_at' => null,
            ],
            17 => [
                'parent_id'  => null,
                'order'      => 2,
                'name'       => 'Advertising',
                'color'      => '#2ECC71',
                'slug'       => 'advertising',
                'created_at' => null,
                'updated_at' => null,
            ],
            18 => [
                'parent_id'  => null,
                'order'      => 3,
                'name'       => 'Beauty',
                'color'      => '#9B59B6',
                'slug'       => 'beauty',
                'created_at' => null,
                'updated_at' => null,
            ],
            19 => [
                'parent_id'  => null,
                'order'      => 4,
                'name'       => 'Health Care',
                'color'      => '#E67E22',
                'slug'       => 'health_care',
                'created_at' => null,
                'updated_at' => null,
            ],
            20 => [
                'parent_id'  => null,
                'order'      => 1,
                'name'       => 'Fashion',
                'color'      => '#3498DB',
                'slug'       => 'fashion',
                'created_at' => null,
                'updated_at' => null,
            ],
            21 => [
                'parent_id'  => null,
                'order'      => 2,
                'name'       => 'Education',
                'color'      => '#2ECC71',
                'slug'       => 'education',
                'created_at' => null,
                'updated_at' => null,
            ],
            22 => [
                'parent_id'  => null,
                'order'      => 3,
                'name'       => 'Food Processing',
                'color'      => '#9B59B6',
                'slug'       => 'food_processing',
                'created_at' => null,
                'updated_at' => null,
            ],
            23 => [
                'parent_id'  => null,
                'order'      => 4,
                'name'       => 'Waste Disposal',
                'color'      => '#E67E22',
                'slug'       => 'waste_disposal',
                'created_at' => null,
                'updated_at' => null,
            ],
            24 => [
                'parent_id'  => null,
                'order'      => 1,
                'name'       => 'Franchising',
                'color'      => '#3498DB',
                'slug'       => 'franchising',
                'created_at' => null,
                'updated_at' => null,
            ],
            25 => [
                'parent_id'  => null,
                'order'      => 2,
                'name'       => 'Wholesale/Retail Sales',
                'color'      => '#2ECC71',
                'slug'       => 'wholesale_retail_sales',
                'created_at' => null,
                'updated_at' => null,
            ],
            26 => [
                'parent_id'  => null,
                'order'      => 3,
                'name'       => 'Waste Management',
                'color'      => '#9B59B6',
                'slug'       => 'waste_mgt',
                'created_at' => null,
                'updated_at' => null,
            ],
            27 => [
                'parent_id'  => null,
                'order'      => 4,
                'name'       => 'Mass Media',
                'color'      => '#E67E22',
                'slug'       => 'mass_media',
                'created_at' => null,
                'updated_at' => null,
            ],
            28 => [
                'parent_id'  => null,
                'order'      => 1,
                'name'       => 'Conulting',
                'color'      => '#3498DB',
                'slug'       => 'consulting',
                'created_at' => null,
                'updated_at' => null,
            ],
            29 => [
                'parent_id'  => null,
                'order'      => 2,
                'name'       => 'Legal Services',
                'color'      => '#2ECC71',
                'slug'       => 'legal_services',
                'created_at' => null,
                'updated_at' => null,
            ],
            30 => [
                'parent_id'  => null,
                'order'      => 3,
                'name'       => 'Public Health',
                'color'      => '#9B59B6',
                'slug'       => 'public_health',
                'created_at' => null,
                'updated_at' => null,
            ],
            31 => [
                'parent_id'  => null,
                'order'      => 4,
                'name'       => 'Gambling',
                'color'      => '#E67E22',
                'slug'       => 'gambling',
                'created_at' => null,
                'updated_at' => null,
            ],
            32 => [
                'parent_id'  => null,
                'order'      => 1,
                'name'       => 'Mining',
                'color'      => '#3498DB',
                'slug'       => 'mining',
                'created_at' => null,
                'updated_at' => null,
            ],
            33 => [
                'parent_id'  => null,
                'order'      => 2,
                'name'       => 'Overseas Remittances/Forex',
                'color'      => '#2ECC71',
                'slug'       => 'overseas_remittances_forex',
                'created_at' => null,
                'updated_at' => null,
            ],
            34 => [
                'parent_id'  => null,
                'order'      => 3,
                'name'       => 'Haulage/Logostics',
                'color'      => '#9B59B6',
                'slug'       => 'haulage_logistics',
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);
    }
}
